import esbuild from "esbuild";
import process from "process";
import { cpSync, mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { get } from "node:https";
import { gzipSync } from "node:zlib";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source files are in the "src" directory.
*/
`;

const prod = (process.argv[2] === "production");
/** 仅生成 accentsData.ts 不打包（供 typecheck/build 前准备依赖） */
const prepareOnly = process.argv.includes("--prepare-accents");

const STATIC_ASSETS = ["manifest.json", "styles.css"];

const ACCENTS_URL =
	"https://raw.githubusercontent.com/mifunetoshiro/kanjium/master/data/source_files/raw/accents.txt";
/** accents.txt 本地缓存（离线构建复用，gitignore） */
const ACCENTS_CACHE_PATH = ".cache/accents.txt";
/** 构建生成的字面量模块（供 bundle 引入，gitignore） */
const ACCENTS_DATA_PATH = "src/dictionary/data/accentsData.ts";

function syncStaticAssets() {
	mkdirSync("dist", { recursive: true });
	for (const name of STATIC_ASSETS) {
		cpSync(name, `dist/${name}`);
	}
}

/**
 * 下载 kanjium accents.txt 到 .cache/accents.txt（已存在则跳过，离线可手动放入）。
 * 返回 accents.txt 全文（读自缓存或本次下载）。
 */
function downloadAccents() {
	return new Promise((resolve) => {
		mkdirSync(".cache", { recursive: true });
		if (existsSync(ACCENTS_CACHE_PATH)) {
			console.log(`[build] ${ACCENTS_CACHE_PATH} 已存在，跳过下载`);
			resolve();
			return;
		}
		const req = get(ACCENTS_URL, (res) => {
			if (res.statusCode !== 200) {
				console.warn(
					`[build] 下载 accents.txt 失败: HTTP ${res.statusCode}（可手动放入 ${ACCENTS_CACHE_PATH}）`,
				);
				resolve();
				return;
			}
			const chunks = [];
			res.on("data", (c) => chunks.push(c));
			res.on("end", () => {
				writeFileSync(ACCENTS_CACHE_PATH, Buffer.concat(chunks));
				console.log(`[build] 已下载 accents.txt -> ${ACCENTS_CACHE_PATH}`);
				resolve();
			});
		});
		req.on("error", (e) => {
			console.warn(`[build] 下载 accents.txt 出错: ${e.message}（可手动放入 ${ACCENTS_CACHE_PATH}）`);
			resolve();
		});
		req.end();
	});
}

/**
 * 把 .cache/accents.txt 全文 gzip 压缩 + base64 编码，写入字符串字面量模块
 * src/dictionary/data/accentsData.ts，供 bundle 以 import 引入。
 * 运行时用 DecompressionStream 解压后喂给 AccentDb.load。
 * gzip+base64 比明文 JSON 字面量小约 66%，缩小 main.js 体积。
 * 文件缺失时写入空串，声调功能静默降级。
 */
function writeAccentsDataModule() {
	let text = "";
	if (existsSync(ACCENTS_CACHE_PATH)) {
		text = readFileSync(ACCENTS_CACHE_PATH, "utf8");
	} else {
		console.warn(`[build] ${ACCENTS_CACHE_PATH} 不存在，生成空 accents 数据模块`);
	}
	// gzip 压缩 → base64 编码（ASCII 安全，可直接嵌入 JS 字符串字面量）
	const gzB64 = gzipSync(Buffer.from(text, "utf8")).toString("base64");
	writeFileSync(ACCENTS_DATA_PATH, `export const ACCENTS_B64_GZ = ${JSON.stringify(gzB64)};\n`);
	console.log(`[build] 已生成 accents 数据模块 -> ${ACCENTS_DATA_PATH} (源文本 ${text.length} 字符，压缩+base64后 ${gzB64.length} 字符)`);
}

function cleanDist() {
	rmSync("dist", { recursive: true, force: true });
}

if (prod) {
	cleanDist();
}

/** 下载 accents.txt 并生成 accentsData.ts（bundle 需 import，必须在 rebuild 前完成） */
async function prepareAccents() {
	await downloadAccents();
	writeAccentsDataModule();
}

// 仅准备 accentsData.ts（typecheck/build 前调用，避免 tsc 因缺失模块报错）后退出
if (prepareOnly) {
	await prepareAccents();
	process.exit(0);
}

const context = await esbuild.context({
	entryPoints: ["src/main.ts"],
	banner: { js: banner },
	target: "es2018",
	platform: "browser",
	format: "cjs",
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	minify: prod
});

/** accentsData.ts 是否已存在（避免打包阶段重复生成） */
const accentsDataExists = existsSync(ACCENTS_DATA_PATH);

if (prod) {
	if (!accentsDataExists) {
		await prepareAccents();
	}
	await context.rebuild();
	syncStaticAssets();
	process.exit(0);
} else {
	if (!accentsDataExists) {
		await prepareAccents();
	}
	syncStaticAssets();
	await context.watch();
}
