import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync, mkdirSync, rmSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source files are in the "src" directory.
*/
`;

const prod = (process.argv[2] === "production");

const STATIC_ASSETS = ["manifest.json", "styles.css"];

function syncStaticAssets() {
	mkdirSync("dist", { recursive: true });
	for (const name of STATIC_ASSETS) {
		cpSync(name, `dist/${name}`);
	}
}

function cleanDist() {
	rmSync("dist", { recursive: true, force: true });
}

if (prod) {
	cleanDist();
}

const context = await esbuild.context({
	entryPoints: ["src/main.ts"],
	banner: { js: banner },
	target: "es2018",
	platform: "node",
	format: "cjs",
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	minify: prod
});

if (prod) {
	await context.rebuild();
	syncStaticAssets();
	process.exit(0);
} else {
	syncStaticAssets();
	await context.watch();
}
